version: "2.1"
services:
  control-dev-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "alembic upgrade head & python3 run_server.py"
    ports:
      - 8080:8000
    environment:
      API_ENV: dev
      RDS_HOSTNAME: robot-control-database-dev.cfpdcop7a57p.ap-northeast-2.rds.amazonaws.com
      RDS_PORT: 3306
      RDS_DB_NAME: robot_control_database
      RDS_USERNAME: admin
      RDS_PASSWORD: Sbqlfflxl10!

      ORDER_SERVER_URL: "http://3.38.89.77:8000/api"
      GLOBAL_PLANNING_SERVER_URL: "http://ec2-3-34-129-43.ap-northeast-2.compute.amazonaws.com:8000"
