version: "2.1"
services:
  control-prod-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "alembic upgrade head & python3 run_server.py"
    ports:
      - 8000:8000
    environment:
      API_ENV: prod
      RDS_HOSTNAME: samsung-control-dev.cfpdcop7a57p.ap-northeast-2.rds.amazonaws.com
      RDS_PORT: 3306
      RDS_DB_NAME: samsung_control_dev
      RDS_USERNAME: neubility
      RDS_PASSWORD: neubility

      ORDER_SERVER_URL: "https://order.neubie.ai/api"
      GLOBAL_PLANNING_SERVER_URL: "https://api.neubie.ai/planning"
